apiVersion: v1
kind: Service
metadata:
  name: {{ include "fast-food.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  {{- if eq .Values.app.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    {{- if .Values.nlbName }}
    service.beta.kubernetes.io/aws-load-balancer-name: {{ .Values.nlbName | quote }}
    {{- else }}
    service.beta.kubernetes.io/aws-load-balancer-name: "fast-food-{{ .Values.app.name }}-nlb"
    {{- end }}
  {{- end }}
  labels:
    {{- include "fast-food.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "fast-food.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fast-food.fullname" . }}-clusterip
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fast-food.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.app.service.targetPort }}
    targetPort: {{ .Values.app.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "fast-food.selectorLabels" . | nindent 4 }}
